name: Build and Package RPFXplorer  
  
on:  
  push:  
    branches: [ main, Joy ]  
  pull_request:  
    branches: [ main, Joy ]  
  
jobs:  
  build:  
    runs-on: windows-latest  
      
    steps:  
    - name: Checkout repository  
      uses: actions/checkout@v4  
      with:  
        submodules: recursive  
      
    - name: Setup vcpkg  
      run: |  
        git clone https://github.com/microsoft/vcpkg.git  
        .\vcpkg\bootstrap-vcpkg.bat  
        .\vcpkg\vcpkg integrate install  
        echo "VCPKG_ROOT=${{ github.workspace }}\vcpkg" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append  
      
    - name: Install dependencies from vcpkg.json  
      run: |  
        .\vcpkg\vcpkg install --triplet=x64-windows  
      
    - name: Setup MSBuild  
      uses: microsoft/setup-msbuild@v1.1  
      
    - name: Install Premake5  
      run: |  
        Invoke-WebRequest -Uri "https://github.com/premake/premake-core/releases/download/v5.0.0-beta2/premake-5.0.0-beta2-windows.zip" -OutFile premake.zip  
        Expand-Archive premake.zip -DestinationPath premake  
        echo "${{ github.workspace }}\premake" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append  
      
    - name: Generate Visual Studio solution  
      run: premake5 vs2022  
      
    - name: Build Release configuration  
      run: msbuild RPFXplorer.sln /p:Configuration=Release /p:Platform=Win64 /m  
      
    - name: Setup WiX Toolset  
      run: |  
        dotnet tool install --global wix  
        wix extension add WixToolset.UI.wixext  
      
    - name: Build MSI installer  
      run: |  
        cd MSI  
        wix build RPFXplorer.wxs -out RPFXplorer.msi  
      
    - name: Package uninstaller script  
      run: |  
        New-Item -ItemType Directory -Force -Path uninstaller  
        Copy-Item disable_extension.bat uninstaller/  
        echo "Run disable_extension.bat as administrator to uninstall RPFXplorer Shell Extension" | Out-File -FilePath uninstaller/README.txt  
        Compress-Archive -Path uninstaller/* -DestinationPath RPFXplorer-Uninstaller.zip  
      
    - name: Upload Release binaries  
      uses: actions/upload-artifact@v4  
      with:  
        name: RPFXplorer-Binaries  
        path: |  
          bin/Release/shellext/rpfxplr.dll  
          bin/Release/rpf.dll  
          bin/Release/libcrypto-3-x64.dll  
          bin/Release/tools/aulens.exe  
          bin/Release/tools/modlense.exe  
      
    - name: Upload MSI installer  
      uses: actions/upload-artifact@v4  
      with:  
        name: RPFXplorer-Installer  
        path: MSI/RPFXplorer.msi  
      
    - name: Upload Uninstaller package  
      uses: actions/upload-artifact@v4  
      with:  
        name: RPFXplorer-Uninstaller  
        path: RPFXplorer-Uninstaller.zip